### PR TITLE
[feature] adds validation supports

### PR DESCRIPTION
**Pull request by apaganobeleno**
@markbates this one adds validate support to tags as we discussed on #4, looking forward for your feedback.

### CODE REVIEW

**Comment by markbates** [comment]
I keep getting a panic:

```
2017/03/20 16:13:41 http: panic serving 127.0.0.1:55515: interface conversion: interface {} is map[string][]string, not []string
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc420430000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x46e60a0, 0xc4201e0bc0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gobuffalo/tags/form/bootstrap.divWrapper(0xc420377b00, 0xc4203c1d28, 0xc4204720c6)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/tags/form/bootstrap/common.go:23 +0xa46
github.com/gobuffalo/tags/form/bootstrap.FormFor.InputTag(0xc4201ecba0, 0xc4204720c6, 0x5, 0xc420377b00, 0x0)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/tags/form/bootstrap/form_for.go:53 +0x1c0
```

**Comment by markbates** [comment]
I'm using the https://github.com/gobuffalo/toodo/blob/master/README.md app

**Comment by apaganobeleno** [comment]
@markbates can you share some code to check how are you passing the errors to the form ?

**Comment by markbates** [comment]
https://github.com/gobuffalo/toodo

Nothing special. I just ran the app as is, and hit the panic.

**Comment by markbates** [comment]
https://github.com/markbates/validate/blob/master/validate.go#L13

Errors is `map[string][]string` not a `[]string`.

**Comment by apaganobeleno** [comment]
Thats right, but before that i extract the errors for a particular field and put it inside the errors options of the field.

https://github.com/apaganobeleno/tags/blob/features/errors-support/form/bootstrap/form_for.go#L80

**Comment by apaganobeleno** [comment]
@markbates i just cloned the repo and seems to run ok as it is, is there any change you have done locally to it ?

**Comment by markbates** [comment]
The problem might be with a bug I fixed a couple of hours ago in plush. https://github.com/gobuffalo/plush/commit/72b43706fc84fcebd06cac6cbea9fcebda053ab4 I never passed any errors into the form, so it was picking up the one set on the context, which is of the wrong type. I'll try this again in a few minutes with the plush fix and let you know what happens.

**Comment by apaganobeleno** [comment]
Oh got it, anyways i have not covered the cases where the wrong type is passed on the "errors" key of the options map, should we simply ignore it ? i appreciate your advise

**Comment by markbates** [comment]
We shouldn't panic. ;) yeah, it's worth checking the type.

**Comment by markbates** [comment]
Different panic this time:

```
2017/03/20 20:44:27 http: panic serving 127.0.0.1:51952: interface conversion: interface {} is map[string][]string, not *validate.Errors
goroutine 142 [running]:
net/http.(*conn).serve.func1(0xc42013fc20)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x46e5fc0, 0xc420333cc0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/gobuffalo/tags/form.NewFormFor(0x470b7e0, 0xc42044a230, 0xc420360870, 0x1)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/tags/form/form_for.go:36 +0x488
github.com/gobuffalo/tags/form/bootstrap.NewFormFor(0x470b7e0, 0xc42044a230, 0xc420360870, 0xc42049ee80)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/tags/form/bootstrap/form_for.go:88 +0x43
github.com/gobuffalo/plush.BootstrapFormForHelper.func1(0xc420360870, 0xc420378818, 0x409cb33)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/plush/forms.go:32 +0x3d
github.com/gobuffalo/plush.helper(0xc420360870, 0xc420411fc0, 0xc420411fe0, 0xc4201d9b80, 0xc420378848, 0x46f53c0, 0x46df060, 0x1, 0x1)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/plush/forms.go:43 +0x48
github.com/gobuffalo/plush.BootstrapFormForHelper(0x470b7e0, 0xc42044a230, 0xc420360870, 0xc420411fc0, 0xc420411fe0, 0xc4201d9b80, 0x0, 0x0, 0x0, 0x0)
	/Users/markbates/Dropbox/development/gocode/src/github.com/gobuffalo/plush/forms.go:33 +0x95
reflect.Value.call(0x46e1540, 0x47a28e0, 0x13, 0x477b513, 0x4, 0xc4204093e0, 0x3, 0x4, 0xc420411fc0, 0xc420411fe0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
```

```erb
<%= form_for(todo, {action: "/todos", errors: errors}) { %>
  <%= f.InputTag("Title") %>
  <%= f.TextArea("Description", {rows: 10}) %>
  <button class="btn btn-success">Save</button>
<% } %>
```

```go
func (v TodosResource) Create(c buffalo.Context) error {
	t := &models.Todo{}
	err := c.Bind(t)
	if err != nil {
		return err
	}

	tx := c.Value("tx").(*pop.Connection)
	verrs, err := tx.ValidateAndCreate(t)
	if err != nil {
		return err
	}
	if verrs.HasAny() {
		c.Set("todo", t)
		c.Set("errors", verrs.Errors)
		return c.Render(422, r.HTML("todos/new.html"))
	}
	c.Flash().Add("success", "Todo was created successfully")
	return c.Redirect(301, "/todos")
}
```

**Comment by markbates** [comment]
If I change the action to just `c.Set("errors", verrs)` then I get this error:

`could not iterate over *validate.Errors`

**Comment by apaganobeleno** [comment]
ok, good, looking into these, thanks @markbates

**Comment by markbates** [comment]
It would be great if we could support *validate.Errors and map[string][]string. 

I can't wait for this! So much awesome.

**Comment by apaganobeleno** [comment]
@markbates on it, found that this one:
`could not iterate over *validate.Errors` is related with the todo errors for block thats on the view, covering the 2 types we want to support.

**Comment by markbates** [comment]
Woot!!! This is so awesome!! Thank you so much for this!

**Pull request merged**
