### PR TITLE
update to match Bootstrap v4 form validation

### PR DESCRIPTION
**Pull request by alphonse927**
I made this change proposal to match as much as possible how bootstrap validate the form, since B4 uses different classes, I removed the "has-error" on the div and added "is-invalid" on the input tag and "invalid-feedback" on the error message.

### CODE REVIEW

**Comment by markbates** [comment]
does this break compatibility with bootstrap 3? is there a way to have both?

**Comment by alphonse927** [comment]
Yes... This break the compatibility with Bootstrap 3... I made it thinking only on Bootstrap 4.... I will think on some way to have both.

**Comment by alphonse927** [comment]
Adding back the Bootstrap 3 classes using Bootstrap 4 doesn't affect the style, since on B3 those classes doesn't exist, and likewise those B4 classes doesn't exist on B3 so, both can co-exist...

**Comment by paganotoni** [comment]
@markbates merging this one, thanks @alphonse927

**Pull request merged**
