### PR TITLE
Feature/add field name resolver

### PR DESCRIPTION
**Pull request by paganotoni**
This allows to define a function to generate the field name on the FormFor, this will be helpful for nested forms. (FieldsFor)

### CODE REVIEW

**Comment by markbates** [comment]
I don’t really understand this. Can you add some tests that potentially show the benefit of it?

**Comment by paganotoni** [comment]
Wow, that was fast! sure.

**Comment by paganotoni** [comment]
@markbates I added one test, probably it would make much more sense if i show you my current fieldsFor helper implementation: https://github.com/paganotoni/app/blob/master/actions/fields_for.go

**Comment by paganotoni** [comment]
@markbates let me know when you have the chance to look at this one :), hope everything is going great in budapest 👍

**Pull request closed without merging**
